package:
    name: pygenome
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}
build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
source:
  path: ..
requirements:
    build:
        - python
        - pydna
        - requests
        - tqdm
        - prettytable
    run:
        - python
        - pydna
        - appdirs
        - requests
        - tqdm
        - prettytable
test:
  requires:
    - python
    - pytest
    - pydna
    - appdirs
    - requests
    - prettytable
  imports:
    - pygenome
  source_files:
    - tests
    #- pygenome
about:
  home: https://github.com/BjornFJohansson/pygenome
  summary: An object oritented biopython api for the Saccharomyces cerevisiae genome.
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
extra:
  maintainers:
   - "Björn Johansson <bjorn_johansson@bio.uminho.pt>"
