language: objective-c
sudo: false
cache:
 - wget
 - pip
 - brew
 - conda
+before_install:
 - rvm get stable  # work around rvm bug on osx
script:
 - bash ci.sh
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
