language: python
python:
  - "2.7"
install:
  - pip install -e .
before_script:
  - pip install -r requirements.txt
  - pip install coveralls
script:
   - nosetests -w tests -v --with-coverage --with-doctest

deploy:
  provider: pypi
  distributions: "sdist --formats=gztar,zip bdist_wheel"
  user: bjorn
  password:
    secure: "JmOLwHng4XWCCfwdkSfkwIZRzTh1Zhil3ZYDekW/y0kaHhQbXthObdPRAp9zqVhzERxBuPJqz4nMkcp8rNDcX+0maP8EjhT8oLphSAUmbaSpw1yAhELbwO3abxRzlL3pcSiLL2rx+vr2le9t3rGs9skfN9c+pASupbwDSBt+F+o="
  on:
    tags: true
    all_branches: true
    repo: BjornFJohansson/pygenome

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - pydna@googlegroups.com
    on_success: change # default: change
    on_failure: change # default: always
  
#condition: "$TRAVIS_TAG == ^[0-9][.][0-9][.][0-9]"
