sudo: required
language: python
python:
  - "2.7"
before_install:
- export DISPLAY=:99.0
- pip install --upgrade pip
- sudo add-apt-repository ppa:ubuntu-wine/ppa -y
- sudo apt-get update -qq
- sudo apt-get install -qq wine
- wget https://www.python.org/ftp/python/2.7.9/python-2.7.9.amd64.msi --output-document=python.msi
- wine msiexec /i python.msi /qn
- wine c:\\Python27\\python.exe -m pip install pypiwin32
#- wine c:\\Python27\\python.exe ~/.wine/drive_c/Python27/Scripts/pywin32_postinstall.py
#- wget http://biopython.org/DIST/biopython-1.65.win32-py2.7.exe --output-document=biopython.exe
#- wine biopython.exe
#- wine c:\\Python27\\python.exe -m pip install biopython
- wine c:\\Python27\\python.exe -m pip install conda
- wine c:\\Python27\\Scripts\\conda init
- wine c:\\Python27\\Scripts\\conda install --yes biopython
- wine c:\\Python27\\Scripts\\conda install --yes nose
- wine c:\\Python27\\python.exe -c "import Bio;print Bio"
- wine c:\\Python27\\python.exe -m pip install -e .
#- wine c:\\Python27\\python.exe -m pip install nose
- wine c:\\Python27\\Scripts\\nosetests
install:
  - pip install -e .
before_script:
  - pip install -r requirements.txt
  - pip install coveralls
script:
   - nosetests -w tests -v --with-coverage --with-doctest

deploy:
  provider: pypi
  distributions: "sdist --formats=gztar,zip bdist_wheel"
  user: bjorn
  password:
    secure: "JmOLwHng4XWCCfwdkSfkwIZRzTh1Zhil3ZYDekW/y0kaHhQbXthObdPRAp9zqVhzERxBuPJqz4nMkcp8rNDcX+0maP8EjhT8oLphSAUmbaSpw1yAhELbwO3abxRzlL3pcSiLL2rx+vr2le9t3rGs9skfN9c+pASupbwDSBt+F+o="
  on:
    tags: true
    all_branches: true
    repo: BjornFJohansson/pygenome

after_success:
  - coveralls
