package:
    name: pygenome
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  include_recipe: False
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  git_url: .

requirements:
    build:
        - python {{ python }}
        - setuptools
        - setuptools_scm
        - pytest-runner
    run:
        - python {{ python }}
        - pydna
        - appdirs
        - requests
        - tqdm
        - prettytable
        - pickle5       # [py<38]
test:
  requires:
    - pytest
    - pytest-doctestplus
    - requests-mock
    - pytest-cov
    - coverage
    - nbval
  imports:
    - pygenome
  source_files:
    - tests
    - src
about:
  home: https://github.com/BjornFJohansson/pygenome
  summary: An object oritented biopython api for the Saccharomyces cerevisiae genome.
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
extra:
  maintainers:
   - "Björn Johansson <bjorn_johansson@bio.uminho.pt>"
