name: pygenome_build_environment
channels:
- conda-forge
- defaults
- BjornFJohansson
dependencies:
- python

- appdirs
- biopython
- pydna

- setuptools
- pip
- anaconda-client
- conda-build
- conda-verify
