name: pygenome_test_environment
channels:
- conda-forge
- defaults
- BjornFJohansson
dependencies:
- python
- pickle5 # [py<38]
- appdirs
- biopython
- prettytable

- requests
- requests-mock

- ipython
- jupyter

- pytest
- pytest-cov
- pytest-mock
- pytest-runner
- pytest-doctestplus
- nbval

- setuptools
- requests-mock

- pyfiglet
