Chromosome    Size(BP) 
01  A   I     225 000  
02  B   II    815 000  
03  C   III   375 000  
04  D   IV    1 640 000
05  E   V     610 000  
06  F   VI    295 000  
07  G   VII   1 120 000
08  H   VIII  555 000  
09  I   IX    450 000  
10  J   X     745 000  
11  K   XI    680 000  
12  L   XII   1 900 000
13  M   XIII  915 000  
14  N   XIV   785 000  
15  O   XV    1 100 000
16  P   XVI   945 000 

### Strategy 1:

                      UPTAG_primer

                      U1-TAG1-U2-> 
                                 KanMX4
                                      <-D1-TAG2-D2
                                      
                                        DNTAG_primer
                     
                     U1-TAG1-U2-KanMX4-D1-TAG2-D2                 Inner cassette


                      
           UPstream45->
                      U1-TAG1-U2-KanMX4-D1-TAG2-D2
                                                 <-DNstream45
                                                 
                                                
                                                
           UPstream45-U1-TAG1-U2-KanMX4-D1-TAG2-D2-DNstream45     Outer cassette


### Strategy 2:
           
                      UPTAG_primer

                      U1-TAG1-U2-> 
                                 KanMX4
                                      <-DNstream45
                      
                      U1-TAG1-U2-KanMX4-DNstream45                Inner cassette
                                      



                      
           UPstream45->
                      U1-TAG1-U2-KanMX4-DNstream45                Outer cassette
                                      <-DNstream45
                                                 
                                                
                                                
           UPstream45-U1-TAG1-U2-KanMX4-DNstream45






U1: 5′-GATGTCCACGAGGTCTCT-3′

D1: 5′-CGGTGTCGGTCTCGTAG-3′ 

U2: 5′-CGTACGCTGCAGGTCGAC-3′

D2: 5′-ATCGATGAATTCGAGCTCG-3′ 
















Keys:
- 0 rec_num
- 1 ORF_name
- 2 deletion_alias
- 3 essential
- 4 A_confirmation_primer_sequence
- 5 B_confirmation_primer_sequence
- 6 C_confirmation_primer_sequence
- 7 D_confirmation_primer_sequence
- 8 UPTAG_primer_sequence
- 9 DNTAG_primer_sequence
- 10 UPstream45_primer_sequence
- 11 DNstream45_primer_sequence
- 12 UPstream90_primer_sequence
- 13 DNstream90_primer_sequence
- 14 AB_wt_PCR
- 15 AkanB_del_PCR
- 16 CD_wt_PCR
- 17 DkanC_del_PCR
- 18 AD_wt
- 19 AD_del
- 20 AB_del_PCR
- 21 CD_del_PCR
- 22 UPTAG_sequence_20mer
- 23 DNTAG_sequence_20mer

In [1]:
import pickle
import csv
from collections import defaultdict as dd

primers = dd(list)

counter = 0

with open("Deletion_primers_PCR_sizes.txt", 'rt') as csvfile:
    rd = csv.reader(csvfile, delimiter='\t')
    keys = [k.strip() for k in next(rd)]
    next(rd)
    for row in rd:
        counter+=1
        values = [x.strip() for x in row]
        primers[values[1]].append({k:v for k,v in zip(keys,values)})

In [2]:
counter

6363

In [3]:
len(primers)

6132

In [4]:
keys

['rec_num',
 'ORF_name',
 'deletion_alias',
 'essential',
 'A_confirmation_primer_sequence',
 'B_confirmation_primer_sequence',
 'C_confirmation_primer_sequence',
 'D_confirmation_primer_sequence',
 'UPTAG_primer_sequence',
 'DNTAG_primer_sequence',
 'UPstream45_primer_sequence',
 'DNstream45_primer_sequence',
 'UPstream90_primer_sequence',
 'DNstream90_primer_sequence',
 'AB_wt_PCR',
 'AkanB_del_PCR',
 'CD_wt_PCR',
 'DkanC_del_PCR',
 'AD_wt',
 'AD_del',
 'AB_del_PCR',
 'CD_del_PCR',
 'UPTAG_sequence_20mer',
 'DNTAG_sequence_20mer']

The first element in the primers list:

In [5]:
primers["YCR061W"]

[{'rec_num': 'n5782',
  'ORF_name': 'YCR061W',
  'deletion_alias': 'YCR061W_1t',
  'essential': '',
  'A_confirmation_primer_sequence': 'GCACGATCCATGATATAGAAAAATC',
  'B_confirmation_primer_sequence': 'GTAGATTCAAGATCATTCAGAGGGA',
  'C_confirmation_primer_sequence': 'GTTGAATCCTTCCTCATTTTCTTTT',
  'D_confirmation_primer_sequence': 'GAATTGACTGAATGCTGGATAAACT',
  'UPTAG_primer_sequence': 'AAAATAGTGAGAGTAATGGATGTCCACGAGGTCTCTGGTGCTCAGTCATCTTCACTCGTACGCTGCAGGTCGAC',
  'DNTAG_primer_sequence': 'CTATATTCCATGGCTTCACGGTGTCGGTCTCGTAGCAGCTCGCGTAATATACTAGATCGATGAATTCGAGCTCG',
  'UPstream45_primer_sequence': 'TGTACTCTTAATACCCCAACCAAAAACAAAATAGTGAGAGTAATG',
  'DNstream45_primer_sequence': 'TTGAAAGTGAACATGGGGGTAAACCCCCTATATTCCATGGCTTCA',
  'UPstream90_primer_sequence': '',
  'DNstream90_primer_sequence': '',
  'AB_wt_PCR': '937',
  'AkanB_del_PCR': '601',
  'CD_wt_PCR': '771',
  'DkanC_del_PCR': '901',
  'AD_wt': '2328',
  'AD_del': '2160',
  'AB_del_PCR': '',
  'CD_del_PCR': '',
  'UPTAG_sequence_20m

In [6]:
len(primers)

6132

The "UPTAG_sequence_20mer" and "DNTAG_sequence_20mer" can be found in "UPTAG_primer_sequence" and "DNTAG_primer_sequence", respectively.

In [7]:
counter = 0
UPTAGboolset = set()
DNTAGboolset = set()
for genename, primerlist in primers.items():
    for p in primerlist:
        counter+=1
        if p["UPTAG_sequence_20mer"]:
            UPTAGboolset.add(p["UPTAG_sequence_20mer"] in p["UPTAG_primer_sequence"])
        if p["DNTAG_sequence_20mer"]:
            DNTAGboolset.add(p["DNTAG_sequence_20mer"] in p["DNTAG_primer_sequence"])

In [8]:
UPTAGboolset, DNTAGboolset, counter

({True}, {True}, 6363)

In [9]:
U1 = "GATGTCCACGAGGTCTCT"
U2 = "CGTACGCTGCAGGTCGAC"
D1 = "CGGTGTCGGTCTCGTAG"
D2 = "ATCGATGAATTCGAGCTCG"

All "UPTAG_primer_sequence" contain U1 and U2 as expected

All "DNTAG_primer_sequence" contain D1 and D2 as expected

In [10]:
counter = 0
U1boolset = set()
U2boolset = set()
D1boolset = set()
D2boolset = set()
for genename, primerlist in primers.items():
    for p in primerlist:
        counter+=1
        U1boolset.add(U1 in p["UPTAG_primer_sequence"])
        U2boolset.add(U2 in p["UPTAG_primer_sequence"])
        if p["DNTAG_primer_sequence"]:
            D1boolset.add(D1 in p["DNTAG_primer_sequence"])
            D2boolset.add(D2 in p["DNTAG_primer_sequence"])

In [11]:
U1boolset, U2boolset, D1boolset, D2boolset

({True}, {True}, {True}, {True})

In [12]:
from pygenome.saccharomyces_cerevisiae.S288C import gene_dicts
genes, stdgenes = gene_dicts()

In [13]:
indb = []
notindb = []
for genename, primerlist in primers.items():
    for p in primerlist:
        if genename in genes:
            p["InDBase"] = True
            indb.append(genename)
        else:
            p["InDBase"] = False
            notindb.append(genename)

About ten percent of the genes in the deletion collection refer to genes no longer in the genome.

In [14]:
len(indb), len(notindb)

(5853, 510)

In [15]:
from pygenome.saccharomyces_cerevisiae.S288C import data_dir

In [16]:
pFA6a_kanMX4 = pickle.load((data_dir/"pFA6a-kanMX4.pickle").open("rb"))

In [17]:
from pydna.primer import Primer
from pydna.amplify import pcr

In [18]:
uptag_and_dntag = []
uptag_and_dns45 = []

for genename, primerlist in primers.items():
    for p in primerlist:
        upt = Primer(p["UPTAG_primer_sequence"])
        dnt = Primer(p["DNTAG_primer_sequence"])
        dns45 = Primer(p["DNstream45_primer_sequence"])

        upt.id = f"UPTAG_{genename}"
        dnt.id = f"DNTAG_{genename}"
        dns45.id = f"DNstream45_{genename}"
        
        if upt and dnt:
            inner_cassette = pcr(upt, dnt, pFA6a_kanMX4)
            p["Strategy"] = 1
            uptag_and_dntag.append(genename)
        elif upt and dns45:
            inner_cassette = pcr(upt, dns45, pFA6a_kanMX4)
            p["Strategy"] = 2
            uptag_and_dns45.append(genename)
        else:
            print(genename, "no strategy")
        p["Inner_cassette"] = inner_cassette

Most genes were deleted using the Strategy 1, but for about three percent of the deletions there was no DNTAG_primer_sequence entry in the original table.

Instead, the DNstream45_primer_sequence anneals directly to the pFA6a_kanMX4 sequence (Strategy 2).

In [19]:
len(uptag_and_dntag) # Strategy 1

6170

In [20]:
len(uptag_and_dns45) # Strategy 2

193

As there are 6363 entries in the original table, we can conclude that it was possible to amplify an inner cassette for all entries in the table.

In [21]:
assert 6170+193 == counter == 6363

### Outer cassette

In [22]:
no_outer_cassette = []
for genename, primerlist in primers.items():
    for p in primerlist:
    
        ups45 = Primer(p["UPstream45_primer_sequence"])
        ups45.id = f"UPstream45_{genename}"

        dns45 = Primer(p["DNstream45_primer_sequence"])
        dns45.id = f"DNstream45_{genename}"
        
        inner_cassette = p["Inner_cassette"]
        
        try:
            outer_cassette = pcr(ups45, dns45, inner_cassette)
        except ValueError as ve:
            no_outer_cassette.append(genename)

For 354 genes, there was no product from the outer cassette amplification. These genes are on chromosomes 1, 5 and 13 (A, E and M).


In [23]:
len(no_outer_cassette)

354

In [24]:
no_outer_cassette[:10]

['YAL001C',
 'YAL002W',
 'YAL003W',
 'YAL004W',
 'YAL005C',
 'YAL007C',
 'YAL008W',
 'YAL009W',
 'YAL010C',
 'YAL011W']

In [25]:
set(name[:3] for name in no_outer_cassette)

{'YAL', 'YAR', 'YER', 'YML', 'YMR'}

All the 354 genes share a feature. The 3' part of the UPstream45_primer_sequence has the U1 sequence, but for a single nucleotide difference.


    GATGTCCACGAGGTCTCT   Canonical U1 sequence (Winzeler et al. 1999, Giaever et al. 2002, Giaever et al. 2014)
    ||||||||||||X|||||
    GATGTCCACGAGCTCTCT   3' part of UPstream45_primer_sequence for each of the 354 genes w/o outer cassette amplification.



In [26]:
canonic_u1 = "GATGTCCACGAGGTCTCT"
mutated_u1 = "GATGTCCACGAGcTCTCT"
primer_ends_ups45 = []

for genename, primerlist in primers.items():
    for p in primerlist:
        if genename in no_outer_cassette:
            ups45 = p["UPstream45_primer_sequence"]
            primer_ends_ups45.append(ups45[-18:])
        break

In [27]:
set(primer_ends_ups45)

{'GATGTCCACGAGCTCTCT'}

In [28]:
mutated_u1.upper() in set(primer_ends_ups45)

True

In [29]:
genes_with_new_ups45_primer = []

for genename, primerlist in primers.items():
    for p in primerlist:
        if genename in no_outer_cassette:
            ups45 = p["UPstream45_primer_sequence"]
            if mutated_u1.upper() in ups45: 
                p["New_UPstream45_primer_sequence"] = ups45.replace(mutated_u1.upper(), canonic_u1)
                genes_with_new_ups45_primer.append(genename)
            else:
                p["New_UPstream45_primer_sequence"] = ""
        else:
            p["New_UPstream45_primer_sequence"] = ""           

In [30]:
len(genes_with_new_ups45_primer)

354

In [31]:
primers["YAL001C"]

[{'rec_num': 'n406',
  'ORF_name': 'YAL001C',
  'deletion_alias': '',
  'essential': 'essential',
  'A_confirmation_primer_sequence': 'CTTATGCAAATCGAGTTATTGAAGCTG',
  'B_confirmation_primer_sequence': 'TCACCTAAACGGAGCCGAAAAG',
  'C_confirmation_primer_sequence': 'GGCTATTGGGTCAATCATAATTGGTA',
  'D_confirmation_primer_sequence': 'ATGTACAGCGCCACCAAGATATGATT',
  'UPTAG_primer_sequence': 'GATGTCCACGAGGTCTCTACTATATGTGAAGGCATGGCCGTACGCTGCAGGTCGAC',
  'DNTAG_primer_sequence': '',
  'UPstream45_primer_sequence': 'GAGAAGAGGACGTTTGGTTGAAGCCAACTAGCCACAAGAAAAATGGATGTCCACGAGCTCTCT',
  'DNstream45_primer_sequence': 'AACTTTGGTTACATAAAAGTAAAATTTATACACCTCATTTCATTAATCGATGAATTCGAGCTCG',
  'UPstream90_primer_sequence': '',
  'DNstream90_primer_sequence': '',
  'AB_wt_PCR': '338',
  'AkanB_del_PCR': '526',
  'CD_wt_PCR': '277',
  'DkanC_del_PCR': '819',
  'AD_wt': '4030',
  'AD_del': '2002',
  'AB_del_PCR': '',
  'CD_del_PCR': '',
  'UPTAG_sequence_20mer': 'ACTATATGTGAAGGCATGGC',
  'DNTAG_sequence_20mer': '

In [32]:
for genename, primerlist in primers.items():
    for p in primerlist:
        
        ups45 = Primer(p["UPstream45_primer_sequence"])
        ups45.id = f"UPstream45_{genename}"

        dns45 = Primer(p["DNstream45_primer_sequence"])
        dns45.id = f"DNstream45_{genename}"
        
        Newups45 = Primer(p["New_UPstream45_primer_sequence"])
        Newups45.id = f"DNstream45_{genename}"
        
        inner_cassette = p["Inner_cassette"]
        
        try:
            outer_cassette = pcr(ups45, dns45, inner_cassette)
        except ValueError as ve:
            try: 
                outer_cassette = pcr(Newups45, dns45, inner_cassette)
            except ValueError as ve:
                print(genename)
                print(ve)
        p["Outer_cassette"] = outer_cassette

In [37]:
from pydna.assembly import Assembly
from tqdm.notebook import tqdm

The cell below might take a long time (~ 20 min) to run.

In [38]:
cassette_recombination = []
no_cassette_recombination = []

for genename, primerlist in tqdm(primers.items()):
    
    if genename in genes:
        gene = genes[genename]
    else:
        continue
    
    locus = gene.locus()
    
    for p in primerlist:
        
        outer_cassette = p["Outer_cassette"]
        
        asm = Assembly((locus, outer_cassette, locus))      

        candidates = asm.assemble_linear()
        
        try:
            kanmx4_gene = candidates[0]
        except:
            no_cassette_recombination.append(genename)
        else:
            cassette_recombination.append(genename)
        break
        

  0%|          | 0/6132 [00:00<?, ?it/s]

In [39]:
no_cassette_recombination

['YBL066C',
 'YCL001W',
 'YCL005W',
 'YCR026C',
 'YGR216C',
 'YLR451W',
 'YML100W-A',
 'YOL141W']

The gene [YML100W-A](https://www.yeastgenome.org/locus/S000028688) (174bp) in the primer list seem to correspond to a different gene on chromosome 13.

This gene is called [YML099W-A](https://www.yeastgenome.org/locus/S000004567) (330bp) located 3918 bp upstream of YML100W-A. 

The YML099W-A was present in old version(s) of the yeast genome but not in the latest.

To complicate things further, the YML099W-A (330bp) is also present in [UNIPROT](https://www.uniprot.org/uniprot/Q6B2I9). From UNIPROT, there is a link back to Genbank [AY692741.1](https://www.ncbi.nlm.nih.gov/nuccore/AY692741) where the **same** 330 bp sequence is referred to as YML100W-A. 

These contradictions might be due to mislabeling of this gene in the primer list or at some other point. 

The YML099W-A is a dubious gene and overlaps with [ARG81(YML099C)](https://www.yeastgenome.org/locus/S000004565). This means that the KanMX4 cassette in the  YML100W-A deletion strain is likely to inactivate both YML099W-A and ARG81 instead of YML100W-A.

Additionally, there is a protein record in Genbank [Q6B2I9.1](https://www.ncbi.nlm.nih.gov/protein/Q6B2I9.1) where it is claimed (incorrectly) that YML099W-A and YML100W-A are synonyms.

| Gene      | Start | End   | Length(bp) | Comment                              |
|-----------|-------|-------|------------|--------------------------------------|
| YML100W-A | 70138 | 70311 | 174        | Putative protein of unknown function |
| YML099W-A | 74228 | 74558 | 330        | Dubious open reading frame           |


In [51]:
from pyfaidx import Fasta
start, end = 74229-1, 74558
pth = '/home/bjorn/.local/share/pygenome/S288C/chr13.fasta'
YML099W_A = Fasta(str(pth))["BK006946.2"][start:end]
YML099W_A

>BK006946.2:74229-74558
ATGAACAGCGAAAATAGTAAGATAACCTTCAAGCCCAATATTCTAATTAAAGGCGTTTATATATTTGTACTTTATGGTATGTGCATATGTATTGTAAAGAATTATTTCAAGACACAGCTCTTCCAGCTACTGGCTCCGGCTATTCATGAAAAATCCAAAAATAACATATTTATGATAGCATCAGATTCATTTCCCAATCTTTATAAACAGAATACCAATTATCGCCCGGCTCATCCTCTTTCCGTCGCCTCCAAACTTCCAACATTACTTGCCTGGCTCCCCAATAGGAGCCCACTCCACTTTCAGCTAATTTGGCTGCCCATCTTCTAA

In [48]:
len(YML099W_A)

330

In [54]:
YML100W_A = genes["YML100W-A"]

In [58]:
print(YML100W_A.cds.format("fasta"))

>part_id BK006946.2 REGION: 70138..70311
ATGTATAAATGTGTCCCGAGTTATTATTCTAAAGCGGGCACCATTGTAGTAACTTATTGC
GAAATTTCTGCTCTTCTCGTCTCGCTCAAAAATCGCGTTCAGGGTAAAAGGGGCGAAACA
GAGGGCCAGATAGAAATTTCGAGAAAAGCGGGTCACCCCGCCCCTGCATTTTGA


In [60]:
no_cassette_recombination.remove('YML100W-A')
no_cassette_recombination

['YBL066C', 'YCL001W', 'YCL005W', 'YCR026C', 'YGR216C', 'YLR451W', 'YOL141W']

In [136]:
from Bio import Align
aligner = Align.PairwiseAligner(gap_score=-1.0) 
aligner.mode = 'local'

In [137]:
for genename, primerlist in tqdm(primers.items()):
    
    if genename in no_cassette_recombination:
        gene = genes[genename]
    else:
        continue
        
    locus = gene.locus()
        
    for p in primerlist:
        
        ups45 = Primer(p["UPstream45_primer_sequence"])
        ups45.id = f"UPstream45_{genename}"

        dns45 = Primer(p["DNstream45_primer_sequence"])
        dns45.id = f"DNstream45_{genename}"

    alignments = aligner.align(str(ups45.seq).upper(),
                               str(locus.seq).upper())
    
    alignments = aligner.align(str(dns45.seq.upper()),
                               str(locus.seq.rc()).upper())
    
    
    break
     
    

  0%|          | 0/6132 [00:00<?, ?it/s]

In [138]:
gene

Gene SEF1/YBL066C

In [142]:
for alignment in alignments:
    print(alignment.aligned[0])
    print(alignment.aligned[1])
    #print(alignment)
    break

((0, 7), (7, 12), (12, 16), (16, 19), (19, 39), (39, 45))
((1213, 1220), (1222, 1227), (1228, 1232), (1234, 1237), (1238, 1258), (1259, 1265))


In [145]:
alignment.aligned[0][-1][-1]

45

In [147]:
for alignment in alignments:
    print(dns45.seq[alignment.aligned[0][0][0]:alignment.aligned[0][-1][-1]])
    print(locus.seq.reverse_complement()[alignment.aligned[1][0][0]:alignment.aligned[1][-1][-1]])
    break

GATATCAACTTTGGAACAACTCAGAGGTGGATATCCCGTCTTTTA
GATATCATTACTTTTGGAAAACAAGCTCAGAGGTGGATATGCCGTGCTTTTA


In [89]:
slice(*alignment.aligned[0][0])

slice(0, 45, None)

In [93]:
alignment.aligned[1]

((958, 1003),)

| SEF1  | YBL066C |
|-------|---------|
| RER1  | YCL001W |
| LDB16 | YCL005W |
| NPP1  | YCR026C |
| GPI1  | YGR216C |
| LEU3  | YLR451W |
| PPM2  | YOL141W |


    
Gene SEF1/YBL066C
CGTATACAGATTATATTGGCTCTGCGTATACGCATTCTCGTCATG
GATATCAACTTTGGAACAACTCAGAGGTGGATATCCCGTCTTTTA <

Gene LDB16/YCL005W
GCAACTTGTAGGAGGAGAAAGCAGTATATAACTAGCCGCAATATG <
ATTCACTTGTTAGTGCATGAGAAGAAGTAATTGCAATATCACCTA

Gene RER1/YCL001W
AAAAAACCTGCCAAGCCCTGCAGAACAATAACAAGCATGTGAATG
ATATCTATATTTTATCATATGCTTGAATCTGCCTTCTCATAGTTA <

Gene NPP1/YCR026C
TACATATATCTGAAAAGAGGTACAGTATAACACTCTCTATAGATG
GATGCGTCTTTTATTTCATAACGCAGTTGTCCCACCTTAAGCTTA <

Gene GPI1/YGR216C
CAGGAACCTTCGAATTCAGGGCGGTTTATACAGTTAAATGACATG <
AGCTGAAGCAAGAAAACGCTACTTTACTTATAAAAGAAAACGTTA

Gene LEU3/YLR451W
AAAAATCGCTTCGTAACATTAATACAAATTCTTTTTGCAATTATG
TTCGAGGGTAAGTAAACATTACGGCAAAAAAAGAAAAGGACTTTA <

Gene PPM2/YOL141W
GGCCATAAAATTTCGACAACTATAGTGCACATATCTAATACGATG
CACATAGCGAGCTGGCAACCATATCGAATCCCGATAGGAGCATTA <




        
